In [2]:
import numpy as np
import random

In [27]:
#Read: https://docs.scipy.org/doc/numpy/reference/arrays.nditer.html#arrays-nditer
#Example of np.nditer function
a = np.arange(0,60,5).reshape(3,4)
print(a,"\n")
for x in np.nditer(a):
    print(x,end = " " )

[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]] 

0 5 10 15 20 25 30 35 40 45 50 55 

In [29]:
#Ordering is based on memory layout style not on the actual array style
print(a.T,"\n")
for x in np.nditer(a.T):
    print(x, end= " ")

[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]] 

0 5 10 15 20 25 30 35 40 45 50 55 

In [26]:
#Ordering can be specified by "order" which supports "Fortran: F Style and "C" C style when we copy the array
b = a.T.copy()
print(b,"\n")
for x in np.nditer(a.T.copy(order = "C")):
    print(x, end = " ")

[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]] 

0 20 40 5 25 45 10 30 50 15 35 55 

In [30]:
#Ordering in Fortran memory layout
print(b,"\n")
for x in np.nditer(a.T.copy(order = "F")):
    print(x, end = " ")

[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]] 

0 5 10 15 20 25 30 35 40 45 50 55 

In [31]:
#Keep existing ordering
print(b,"\n")
for x in np.nditer(a.T.copy(order = "K")):
    print(x, end = " ")

[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]] 

0 5 10 15 20 25 30 35 40 45 50 55 

In [44]:
#Setting ops flags for modifying values of the reference array
a = np.arange(0,60,5).reshape(3,4)
print(a,"\n")
for x in np.nditer(a, op_flags = ['readwrite']):
    x = x*2
    print(x,end = " ")
print("\n")
print(a)

print("\n","Now with changing input array","\n")
for x in np.nditer(a, op_flags = ['readwrite']):
    x[...] = x*2
    print(x,end = " ")
print("\n")
print(a) #Note input array is changed as well

[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]] 

0 10 20 30 40 50 60 70 80 90 100 110 

[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]

 Now with changing input array 

0 10 20 30 40 50 60 70 80 90 100 110 

[[  0  10  20  30]
 [ 40  50  60  70]
 [ 80  90 100 110]]


In examples above, the iterator was accesing elements of the array one at a time.
Now a way to move the one dimensional innermost loop into code such that it is external to iterator
Allows us to use the vectorized numpy operation

In [48]:
a = np.arange(0,100,10).reshape(5,2)
for x in np.nditer(a,flags = ["external_loop"]):
    print(x, end = " ")

[ 0 10 20 30 40 50 60 70 80 90] 

In [50]:
for x in np.nditer(a,flags = ["external_loop"],order = "F"):
    print(x, end = " ")

[ 0 20 40 60 80] [10 30 50 70 90] 

In [51]:
for x in np.nditer(a,flags = ["external_loop"],order = "C"):
    print(x, end = " ")

[ 0 10 20 30 40 50 60 70 80 90] 

During iteration, you may want to use the index of the current element in a computation. For example, you may want to visit the elements of an array in memory order, but use a C-order, Fortran-order, or multidimensional index to look up values in a different array.

The Python iterator protocol doesn’t have a natural way to query these additional values from the iterator, so we introduce an alternate syntax for iterating with an nditer. This syntax explicitly works with the iterator object itself, so its properties are readily accessible during iteration. With this looping construct, the current value is accessible by indexing into the iterator, and the index being tracked is the property index or multi_index depending on what was requested.

The Python interactive interpreter unfortunately prints out the values of expressions inside the while loop during each iteration of the loop. We have modified the output in the examples using this looping construct in order to be more readable.

How to get the index of current element when iterating?
New syntax that works with the iterator object
- Current value is accessible by indexing into the iterator
- index being tracked is property index

In [ ]:
#Read: https://docs.scipy.org/doc/numpy/reference/arrays.nditer.html#arrays-nditer
#Example of np.nditer function
a = np.arange(96,108,2).reshape(2,3)
it = np.nditer(a, flags = ['f_index'])
while not it.finished:
    print("%d, %d" %(it[0],it.index), it.iternext())

print("----")
it = np.nditer(a, flags=['multi_index'])
while not it.finished:
    print("%d <%s>" %(it[0], it.multi_index),it.iternext(),it.finished)

In [ ]:
a = np.arange(96,108,2).reshape(2,3)
it = np.nditer(a, op_flags = ['readwrite'], flags = ['multi_index'])
while not it.finished:
    print("%d %d" %(it.multi_index[0], it.multi_index[1]),it.iternext(),it.finished)

In [ ]:
a = np.arange(96,108,2).reshape(2,3)
it = np.nditer(a, op_flags = ['readwrite'], flags = ['multi_index'])
while not it.finished:
    it[0] = it.multi_index[1] - it.multi_index[0]
    it.iternext()
a