In [109]:
import numpy as np
import random

In [57]:
def softmax(x):
    inpShape = x.shape
    if(len(inpShape) ==  1):
        # if only dimension, then return e^x/Sum(e^y)
        
        return(np.exp(x - max(x)) / np.sum(np.exp(x - max(x)))) 
        # if two dimensionsional, then return e^x/Sum(e^y) for each column
    elif (len(inpShape) == 2):
            
        return np.exp(x - np.max(x,0)) / np.sum(np.exp(x-np.max(x,0)),0)
        

In [47]:
a = np.array([[1,2],[2,2]])
a- np.max(a,0)


array([[-1,  0],
       [ 0,  0]])

In [53]:
#Simple test code
a = np.array([100,4], dtype = np.float32)
b = np.sum(np.exp(a))
a/b
a = np.array([[1,2],[1,2]])
b = np.exp(a)
c = np.sum(b,0)
a/c

/home/animo/anaconda3/lib/python3.5/site-packages/ipykernel/__main__.py:3: RuntimeWarning: overflow encountered in exp
  app.launch_new_instance()


array([[ 0.18393972,  0.13533528],
       [ 0.18393972,  0.13533528]])

In [54]:
a

array([[1, 2],
       [1, 2]])

In [55]:
b

array([[ 2.71828183,  7.3890561 ],
       [ 2.71828183,  7.3890561 ]])

In [56]:
c

array([  5.43656366,  14.7781122 ])

In [81]:
# Write basic test for the function
def test_softmax_basic():
    print("Basic Tests")
    test1 = softmax(np.array([1,2]))
    print("Test 1:",test1 )
    res1 = np.array([0.26894,0.73106])
    assert np.allclose(test1,res1, rtol = 1e-05, atol = 1e-06)
    
    test2 = softmax(np.array([[1,2],[1,2]]))
    print("Test 2:",test2 )
    res2 = np.array([[0.5,0.5],[ 0.5,  0.5]] )
    assert np.allclose(test2,res2, rtol = 1e-05, atol = 1e-06)
    
    test3 = softmax(np.array([1,2,3,4,5,6,7,8,9]))
    print("Test 3")
    res3 = np.array([0.00021,0.00058,0.00157,0.00426,0.01158,0.03148,0.08556,0.23257,0.63220])
    assert np.allclose(test3,res3, rtol = 1e-5, atol = 1e-05)

In [82]:
test_softmax_basic()

Basic Tests
Test 1: [ 0.26894142  0.73105858]
Test 2: [[ 0.5  0.5]
 [ 0.5  0.5]]
Test 3


In [45]:
test2 = softmax(np.array([[1,2],[1,2]]))
test2

array([[ 0.73105858,  0.73105858],
       [ 0.73105858,  0.73105858]])

In [83]:
def sigmoid(x):
    return(1/(1 + np.exp(-x)))

In [99]:
sigmoid(np.array([[1,2],[2,2]]))

array([[ 0.73105858,  0.88079708],
       [ 0.88079708,  0.88079708]])

In [89]:
def gradient_sigmoid(x):
    #input x has the exponentized function 1/(1+e^-x)
    return(x*(1-x))

In [90]:
gradient_sigmoid(sigmoid(np.array([1,2,3])))

array([ 0.19661193,  0.10499359,  0.04517666])

In [107]:
def test_sigmoid():
    print("Running tests")
    input_value = np.array([[1, 2], [-1, -2]])
    sigmoid_value = sigmoid(input_value)
    gradient = gradient_sigmoid(sigmoid_value)
    test_sigmoid_value = np.array([[0.73105858, 0.88079708],[0.26894142, 0.11920292]])
    assert np.allclose(sigmoid_value,test_sigmoid_value, rtol=1e-05, atol=1e-06)
    print(sigmoid_value)
    
    test_gradient_value = np.array([[0.19661193, 0.10499359],[0.19661193, 0.10499359]])
    assert np.allclose(gradient,test_gradient_value, rtol=1e-05, atol=1e-06)
    print(gradient)

In [108]:
if __name__ == "__main__":
    test_sigmoid()

Running tests
[[ 0.73105858  0.88079708]
 [ 0.26894142  0.11920292]]
[[ 0.19661193  0.10499359]
 [ 0.19661193  0.10499359]]


In [ ]:
def naive_gradient_check(cost_function,input_vector):
    #input cost_function is a function that takes an input and returns the cost(sigmoid) and its gradients
    #input input_vector is the point at which we check the gradient
    
    #<TBD>
    random_state = random.getstate()
    save_state = random.setstate(random_state)
    
    cost, gradient = cost_function(input_vector)
    h = 1e-4
    
    #The way naive gradient check function would work is to calculate {f(x+h)-f(x)}/h
    # That is the definition of a gradient at a point
    
    #Using np.nditer here. Check the npnditer notebook to work through the syntax
    it = np.nditer(input_vector, flags = ["multi_index"], op_flags = ["readwrite"])
    while not it.finished:
        i = it.multi_index
        
        #Calculating naive gradient
        input_vector[0] = (cost_function(input_vector[0] + h) - cost_function(input_vector[0])) / h
        
        it.iternext()
        
    

In [142]:
quad = lambda x: (np.sum(x ** 2), x * 2)
u = quad(np.array(123.456))    
print(u)

u = quad(np.array([1,2,3]))    
print(u)

u = quad(np.random.randn(3,))    
print(u)

(15241.383936, 246.91200000000001)
(14, array([2, 4, 6]))
(0.92800545686052149, array([ -1.67842700e+00,  -9.45992713e-01,   1.55447806e-03]))
